on: workflow_call

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - name: "One"
        run: "echo 1"
      - name: "Two"
        run: "echo 2"
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: "One"
        run: "echo 1"
      - name: "Two"
        run: "echo 2"
