name: Push

on: push

jobs:
  lint:
    name: "Lint"
    uses: justincampbell/github-actions-test/.github/workflows/lint.yml@main
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Job
        run: "true"
